export const blackList: string[] = [
  // Português
  'Sexo',
  'Pornografia',
  'Hentai',
  'Nudez',
  'Erótico',
  'Adulto',
  'XXX',
  'Desnudez',
  'Vídeo para adultos',
  'Conteúdo sexual',
  'Conteúdo explícito',
  'Vulgar',
  'Obsceno',
  'Conteúdo para maiores de 18 anos',
  'Material sexualmente explícito',
  'Palavrão',
  'Conteúdo inadequado',
  'Nudez total',
  'Censurado',
  'Ofensivo',

  // Inglês
  'Sex',
  'Pornography',
  'Hentai',
  'Nudity',
  'Erotic',
  'Adult',
  'XXX',
  'Explicit',
  'Adult video',
  'Sexual content',
  'Explicit content',
  'Vulgar',
  'Obscene',
  '18+ content',
  'Sexually explicit material',
  'Profanity',
  'Inappropriate content',
  'Full nudity',
  'Censored',
  'Offensive',
]
